# Import Libraries

In [1]:
# For drive access
from google.colab import drive
drive.mount('/content/drive')

# Standard libraries
import numpy as np
import pandas as pd
import time

# for audio
import librosa

# for normalization & avgpooling features
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Self defined class method to extract framed audios and extract audio features

In [2]:
class Framed:

  def __init__(self,
               dataframe,
               sr=16000,
               window_size_s=5.0,
               hop_size_s=2.5,
               do_augment=False
               ):
    """
    Instantiate the Framed class, create train and val dfs.

    The extract_framed() method is automatically called when the class is
    instantiated to extract the framed audios and add to the train and val dfs.

    Parameters:
      dataframe (pd.DataFrame): DataFrame containing audio file information.
      sr (int): Sample rate of the audio files.
      window_size_s (float): Window size in seconds for framing the audio.
      hop_size_s (float): Hop size in seconds for framing the audio.
      augment (bool): Whether to apply augmentation to the audio.
    """
    # instantiate class
    self.sr = sr
    self.frame_length = int(window_size_s * sr)
    self.frame_step = int(hop_size_s * sr)

    # split the dataframe to train and val by calling the _split_train_val() method
    self.train_df, self.val_df = self._split_train_val(dataframe)

    # add framed audios to train and val dfs by calling the extract_framed() method
    # only training data could be augmented, validation is never augmented
    self.extract_framed(self.train_df, augment=do_augment)
    self.extract_framed(self.val_df, augment=False)


  ########################################
  # _split_train_val function is called when the class is instantiated
  ########################################
  def _split_train_val(self,
                       dataframe):
    """
    Split the dataframe to train and val based on predefined 'set' column.

    Parameters:
      dataframe (pd.DataFrame): DataFrame containing audio file information.

    Returns:
      tuple: Tuple of train and val dataframes containing audio file information.
    """
    # extract the train set from dataframe & shuffle the train set
    train_df = dataframe[dataframe['set'] == 'train']
    train_df = train_df.sample(frac=1, random_state=1234)

    # extract the val set from dataframe & shuffle the val set
    val_df = dataframe[dataframe['set'] == 'val']
    val_df = val_df.sample(frac=1, random_state=1234)

    return train_df, val_df


  ########################################
  # augment function is called by extract_framed function if do_augment=True
  ########################################
  def augment(self, audio_array):
    """
    Apply random augmentation if needed.

    Parameters:
      audio_array (npy): Training audio array.

    Returns:
      audio_array (npy): Augmented audio array.
    """
    choice = np.random.choice(['original','noise','shift','pitch'])

    # if the audio is short (less than 7 seconds in duration), stretch it first
    if len(audio_array) <= 7*self.sr:
      audio_array = librosa.effects.time_stretch(y=audio_array, rate=np.random.uniform(low=0, high=1))
    # if the audio is not short, apply a random augmentation at random magnitude
    elif choice == 'noise':
      noise_amp = np.random.normal(loc=0.0, scale=0.05)*np.amax(audio_array)
      audio_array = audio_array + noise_amp*np.random.normal(size=audio_array.shape[0])
    elif choice == 'shift':
      shift_range = int(np.random.uniform(low=-5, high=5)*1000)
      audio_array = np.roll(audio_array, shift_range)
    elif choice == 'pitch':
      audio_array = librosa.effects.pitch_shift(y=audio_array, sr=self.sr, n_steps=np.random.uniform(low=0, high=1))
    else:
      audio_array = audio_array

    return audio_array


  ########################################
  # extract_framed function is called when the class is instantiated to extract the framed audios
  ########################################
  def extract_framed(self, dataframe, augment):
    """
    Load audio files from the given DataFrame, extract framed audios,
    and add the framed audios to the given DataFrame

    Parameters:
      dataframe (pd.DataFrame): DataFrame containing audio file information.
      augment (bool): Whether to apply augmentation to the audio.
    """
    # load audios
    audios = []
    for filename in dataframe['filename_npy']:
      audio = np.load('/content/drive/MyDrive/project/train_npy/' + filename)
      # if augment is true, call the augment function to apply augmentation to the audio
      if augment:
        audio = self.augment(audio)
      audios.append(audio)
    assert len(audios) == len(dataframe)

    # extract framed audios
    framed = []
    for audio in audios:
      framed_audio = tf.signal.frame(audio, self.frame_length, self.frame_step, pad_end=False)
      framed.append(framed_audio)
    assert len(framed) == len(audios)

    # add framed audios to df
    dataframe['framed'] = framed

In [3]:
class Extraction:

  def __init__(self,
               train_df,
               val_df,
               sr=16000,
               n_mfccs=20, #20 is the default n_mfccs from librosa
               n_mels=20, #reduced from 128 default from librosa to 20
               n_chroma=12, #12 is the default n_chroma from librosa
               features=['mfcc'],
               do_normalize=True,
               do_avgpool=True #WARNING: THE KERNEL WILL CRASH IF YOU TRY TO EXTRACT ALL FEATURES WITHOUT AVGPOOL
               ):
    """
    Instantiate the Extraction class and extract the labels and features from train and val DataFrames.

    The extract_features() method is automatically called to extract the labels and features from the given DataFrame.

    Parameters:
      train_df (pd.DataFrame): DataFrame containing training data.
      val_df (pd.DataFrame): DataFrame containing validation data.
      sr (int): Sample rate of the audio files.
      n_mfccs (int): Number of MFCCs to extract.
      n_mels (int): Number of Mel bands to extract.
      n_chroma (int): Number of chroma bins to use.
      features (list): List of features to extract.
        accepted features: 'mfcc', 'chroma', 'rms', 'spectral_centroid', 'melspectrogram', 'continent', 'rating', 'type'.
      normalize (bool): Whether to normalize the features.
      maxpool (bool): Whether to maxpool the features.
    """
    # instantiate class variables
    self.sr = sr
    self.n_mfccs = n_mfccs
    self.n_mels = n_mels
    self.n_chroma = n_chroma
    self.do_normalize = do_normalize
    self.do_avgpool = do_avgpool

    # confirm features have been specified
    assert len(features) != 0, "Must Specify At Least One Feature In The Form Of A List."
    self.features = features

    # confirm features are valid
    self.accepted_feature = ['mfcc', 'chroma', 'rms', 'spectral_centroid', 'melspectrogram', 'continent', 'rating', 'type']
    for each in self.features:
      assert each in self.accepted_feature, f"{each} is not an accepted feature, only 'mfcc', 'chroma', 'rms', 'spectral_centroid', 'melspectrogram', 'continent', 'rating', and 'type' are accpeted features."

    # extract train and val labels and features
    self.train_y, self.train_features = self.extract_features(train_df)
    self.val_y, self.val_features = self.extract_features(val_df)

    # process the features by applying normalization or average pooling
    self.train_features, self.val_features = self.process_features(self.train_features, self.val_features)


  ########################################
  # each of the extract_x() function is callable by the extract_features() function based on the features instantiated
  # each of the features are extracted from librosa and transposed to shape (n_time, n_features)
  ########################################
  def extract_mfcc(self, each):
    return np.transpose(librosa.feature.mfcc(y=np.array(each), sr=self.sr, n_mfcc=self.n_mfccs))

  def extract_chroma(self, each):
    return np.transpose(librosa.feature.chroma_stft(y=np.array(each), sr=self.sr, n_chroma=self.n_chroma))

  def extract_rms(self, each):
    return np.transpose(librosa.feature.rms(y=np.array(each)))

  def extract_spectral_centroid(self, each):
    return np.transpose(librosa.feature.spectral_centroid(y=np.array(each), sr=self.sr))

  def extract_melspectrogram(self, each):
    mel = librosa.feature.melspectrogram(y=np.array(each), sr=self.sr, n_mels=self.n_mels)
    return np.transpose(librosa.power_to_db(mel))


  ########################################
  # normalization function is called by process_features() function for the features that require normalization
  ########################################
  def normalization(self, train_X, val_X, n_time, n_features):
    """
    Normalize the train and val features

    Parameters:
      train_X (npy): Training feature
      val_X (npy): Validation feature
      n_time (int): Time axis
      n_features (int): Feature axis

    Returns:
      train_X (npy): Normalized training feature
      val_X (npy): Normalized validation feature
    """
    # flatten the np arrays to 1D
    train_X_reshape = train_X.reshape(-1, n_time * n_features)
    val_X_reshape = val_X.reshape(-1, n_time * n_features)

    # use minmaxscaler to normalize the train and val features
    scaler = MinMaxScaler((0,1)).fit(train_X_reshape)
    train_X_scaled = scaler.transform(train_X_reshape)
    val_X_scaled = scaler.transform(val_X_reshape)

    # reshape the features to the original shape (n_time, n_features)
    train_X = train_X_scaled.reshape(-1, n_time, n_features)
    val_X = val_X_scaled.reshape(-1, n_time, n_features)

    return train_X, val_X


  ########################################
  # avgpooling function is called by process_features() function for the features that require average pooling
  ########################################
  def avgpooling(self, train_X, val_X, n_time, n_features):
    """
    Average pooling the train and val features

    Parameters:
      train_X (npy): Training feature
      val_X (npy): Validation feature
      n_time (int): Time axis
      n_features (int): Feature axis

    Returns:
      train_X (npy): Avgpooled training feature
      val_X (npy): Avgpooled validation feature
    """
    # instantiate the keras layers and model.
    # the model only performs average pooling of inputs
    tf.keras.backend.clear_session()
    input = tf.keras.layers.Input(shape=(n_time, n_features))
    global_avg_pooling = tf.keras.layers.GlobalAveragePooling1D()
    pooled = global_avg_pooling(input)
    pooling_model = tf.keras.models.Model(inputs=input, outputs=pooled)

    # use the instantiated model to avgpool the train and val features
    train_X = pooling_model.predict(train_X)
    val_X = pooling_model.predict(val_X)

    return train_X, val_X


  ########################################
  # process_features function is called when the class is instantiated
  ########################################
  def process_features(self, train_features_dict, val_features_dict):
    """
    Apply normalization or average pooling to train and val features

    Parameters:
      train_features_dict (dict): Dictionary containing the training features
      val_features_dict (dict): Dictionary containing the validation features

    Returns:
      tuple: Tuple containing normalized and/or average pooled training and validation features dictionary
    """
    start_time = time.time()
    display('features processing started ---------->')

    for each in train_features_dict.keys():
      # 'continent', 'rating', and 'type' do not need to be processed
      if each == 'continent' or each == 'rating' or each == 'type':
        pass
      # process numeric features
      else:
        if each == 'mfcc':
          n_features=self.n_mfccs
        elif each == 'chroma':
          n_features=self.n_chroma
        elif each == 'rms' or each == 'spectral_centroid':
          n_features=1
        elif each == 'melspectrogram':
          n_features=self.n_mels

        # index the dictionary to find the value of the feature based on the feature name (key)
        train_feature = train_features_dict[each]
        val_feature = val_features_dict[each]

        # call normalization or avgpooling function to apply normalization or average pooling to features
        if self.do_normalize and self.do_avgpool:
          train_features_dict[each], val_features_dict[each] = self.normalization(train_feature, val_feature, n_time=train_feature.shape[1], n_features=n_features)
          train_features_dict[each], val_features_dict[each] = self.avgpooling(train_features_dict[each], val_features_dict[each], n_time=train_feature.shape[1], n_features=n_features)
        elif self.do_normalize:
          train_features_dict[each], val_features_dict[each] = self.normalization(train_feature, val_feature, n_time=train_feature.shape[1], n_features=n_features)
        elif self.do_avgpool:
          train_features_dict[each], val_features_dict[each] = self.avgpooling(train_feature, val_feature, n_time=train_feature.shape[1], n_features=n_features)
        else:
          train_features_dict[each], val_features_dict[each] = train_features_dict[each], val_features_dict[each]

        display(f'{each} processed')

    end_time = time.time()
    display(f'features processing took {(end_time - start_time)/60:.1f} mins')

    return train_features_dict, val_features_dict


  ########################################
  # extract_features function is called when the class is instantiated
  ########################################
  def extract_features(self, dataframe):
    """
    Extract the label & features from the dataframes

    Parameters:
      dataframe (pd.DataFrame): DataFrame containing audio file information

    Returns:
      tuple: Tuple containing labels and a dictionary of extracted features
    """
    start_time = time.time()
    display(f'feature extraction started ---------->')

    # create empty list and dict to store the labels and features
    y = []
    features_dict = {item: [] for item in self.features}

    # iterate through each row of the dataframe to extract the label and features
    for _, row in dataframe.iterrows():
      label = row['primary_label']
      framed = row['framed']

      for each in framed:
        y.append(label)

        if 'continent' in self.features:
          features_dict['continent'].append(row['continent'])
        if 'rating' in self.features:
          features_dict['rating'].append(row['rating'])
        if 'type' in self.features:
          features_dict['type'].append(row['type'])

        # dynatically call the extract_x function to extract the listed features
        for feature in self.features:
          extract = f"extract_{feature}"
          if hasattr(self, extract) and callable(func := getattr(self, extract)):
            features_dict[feature].append(func(each))

    # cast lists to np arrays
    for each in features_dict.keys():
      features_dict[each] = np.array(features_dict[each])
    y = np.array(y)

    end_time = time.time()
    display(f'features extraction took {(end_time - start_time)/60:.1f} mins')

    return y, features_dict


# Load train_val.csv & create example_df to test the class methods

In [4]:
df = pd.read_csv('/content/drive/MyDrive/project/train_val.csv')

df.head()

primary_label   type  latitude  longitude  rating             filename  \
0        comsan   call   51.9612     5.8104     2.0  comsan/XC528482.ogg   
1        comsan   call   51.4522    -9.8189     4.0  comsan/XC667665.ogg   
2        comsan   call   49.4452    22.6154     4.0  comsan/XC578772.ogg   
3        comsan  blank   53.9299    -2.9833     2.5  comsan/XC702785.ogg   
4        comsan   call   37.1379    -7.6303     3.0  comsan/XC494789.ogg   

    duration country continent         filename_npy    set  
0  18.233500      NL    EUROPE  comsan/XC528482.npy  train  
1   6.556000      IE    EUROPE  comsan/XC667665.npy  train  
2  31.268563      PL    EUROPE  comsan/XC578772.npy  train  
3  55.431875      GB    EUROPE  comsan/XC702785.npy  train  
4   5.760000      PT    EUROPE  comsan/XC494789.npy  train

In [5]:
example_df = pd.concat([df.head(5), df.tail(5)])
example_df

primary_label   type  latitude  longitude  rating              filename  \
0           comsan   call   51.9612     5.8104     2.0   comsan/XC528482.ogg   
1           comsan   call   51.4522    -9.8189     4.0   comsan/XC667665.ogg   
2           comsan   call   49.4452    22.6154     4.0   comsan/XC578772.ogg   
3           comsan  blank   53.9299    -2.9833     2.5   comsan/XC702785.ogg   
4           comsan   call   37.1379    -7.6303     3.0   comsan/XC494789.ogg   
1039       eaywag1   call   52.7354    -0.6666     4.0  eaywag1/XC492232.ogg   
1040       eaywag1   call   56.2566    12.5237     3.0  eaywag1/XC593974.ogg   
1041       eaywag1   call   45.0243    34.1899     3.0  eaywag1/XC569651.ogg   
1042        comsan   call   59.3794    24.2407     3.0   comsan/XC579372.ogg   
1043        comsan   call   43.7412    -7.8670     5.0   comsan/XC644655.ogg   

       duration country continent          filename_npy    set  
0     18.233500      NL    EUROPE   comsan/XC528482.npy  train  
1      6.556000      IE    EUROPE   comsan/XC667665.npy  train  
2     31.268563      PL    EUROPE   comsan/XC578772.npy  train  
3     55.431875      GB    EUROPE   comsan/XC702785.npy  train  
4      5.760000      PT    EUROPE   comsan/XC494789.npy  train  
1039   8.019625      GB    EUROPE  eaywag1/XC492232.npy    val  
1040  11.016000      SE    EUROPE  eaywag1/XC593974.npy    val  
1041  18.912688      UA    EUROPE  eaywag1/XC569651.npy    val  
1042   7.105000      EE    EUROPE   comsan/XC579372.npy    val  
1043   5.929812      ES    EUROPE   comsan/XC644655.npy    val

In [6]:
example_df['duration'].sort_values()

4        5.760000
1043     5.929812
1        6.556000
1042     7.105000
1039     8.019625
1040    11.016000
0       18.233500
1041    18.912688
2       31.268563
3       55.431875
Name: duration, dtype: float64

In [7]:
%%time

framed = Framed(example_df,
               window_size_s=5.0,
               hop_size_s=2.5,
               do_augment=True)

CPU times: user 2.83 s, sys: 316 ms, total: 3.14 s
Wall time: 5.61 s


In [8]:
framed.train_df

primary_label   type  latitude  longitude  rating             filename  \
4        comsan   call   37.1379    -7.6303     3.0  comsan/XC494789.ogg   
0        comsan   call   51.9612     5.8104     2.0  comsan/XC528482.ogg   
1        comsan   call   51.4522    -9.8189     4.0  comsan/XC667665.ogg   
2        comsan   call   49.4452    22.6154     4.0  comsan/XC578772.ogg   
3        comsan  blank   53.9299    -2.9833     2.5  comsan/XC702785.ogg   

    duration country continent         filename_npy    set  \
4   5.760000      PT    EUROPE  comsan/XC494789.npy  train   
0  18.233500      NL    EUROPE  comsan/XC528482.npy  train   
1   6.556000      IE    EUROPE  comsan/XC667665.npy  train   
2  31.268563      PL    EUROPE  comsan/XC578772.npy  train   
3  55.431875      GB    EUROPE  comsan/XC702785.npy  train   

                                              framed  
4  ((tf.Tensor(-1.2212125e-05, shape=(), dtype=fl...  
0  ((tf.Tensor(-0.0029895390239467307, shape=(), ...  
1  ((tf.Tensor(1.4402971e-05, shape=(), dtype=flo...  
2  ((tf.Tensor(-0.00014392172171481495, shape=(),...  
3  ((tf.Tensor(0.0005660690803182515, shape=(), d...

In [9]:
framed.val_df

primary_label  type  latitude  longitude  rating              filename  \
1043        comsan  call   43.7412    -7.8670     5.0   comsan/XC644655.ogg   
1039       eaywag1  call   52.7354    -0.6666     4.0  eaywag1/XC492232.ogg   
1040       eaywag1  call   56.2566    12.5237     3.0  eaywag1/XC593974.ogg   
1041       eaywag1  call   45.0243    34.1899     3.0  eaywag1/XC569651.ogg   
1042        comsan  call   59.3794    24.2407     3.0   comsan/XC579372.ogg   

       duration country continent          filename_npy  set  \
1043   5.929812      ES    EUROPE   comsan/XC644655.npy  val   
1039   8.019625      GB    EUROPE  eaywag1/XC492232.npy  val   
1040  11.016000      SE    EUROPE  eaywag1/XC593974.npy  val   
1041  18.912688      UA    EUROPE  eaywag1/XC569651.npy  val   
1042   7.105000      EE    EUROPE   comsan/XC579372.npy  val   

                                                 framed  
1043  ((tf.Tensor(-7.086841e-06, shape=(), dtype=flo...  
1039  ((tf.Tensor(8.97795e-06, shape=(), dtype=float...  
1040  ((tf.Tensor(2.6969647e-06, shape=(), dtype=flo...  
1041  ((tf.Tensor(3.4074765e-07, shape=(), dtype=flo...  
1042  ((tf.Tensor(6.3799234e-06, shape=(), dtype=flo...

In [10]:
features_list = ['mfcc', 'chroma', 'rms', 'spectral_centroid', 'melspectrogram', 'continent', 'type', 'rating']

In [11]:
%%time

features = Extraction(framed.train_df,
                      framed.val_df,
                      features=features_list,
                      do_normalize=True,
                      do_avgpool=True)

'feature extraction started ---------->'

/usr/local/lib/python3.10/dist-packages/librosa/core/pitch.py:101: UserWarning: Trying to estimate tuning from empty frequency set.
  return pitch_tuning(


'features extraction took 0.1 mins'

'feature extraction started ---------->'

'features extraction took 0.0 mins'

'features processing started ---------->'

1/1 [==============================] - 0s 22ms/step


'mfcc processed'

1/1 [==============================] - 0s 19ms/step


'chroma processed'

1/1 [==============================] - 0s 18ms/step


'rms processed'

1/1 [==============================] - 0s 19ms/step


'spectral_centroid processed'

1/1 [==============================] - 0s 19ms/step


'melspectrogram processed'

'features processing took 0.0 mins'

CPU times: user 6.04 s, sys: 2.99 s, total: 9.03 s
Wall time: 10.5 s


In [12]:
train_y = features.train_y

display(train_y.shape)
display(train_y[:5])

(40,)

array(['comsan', 'comsan', 'comsan', 'comsan', 'comsan'], dtype='<U6')

In [13]:
train_features = features.train_features

for key in train_features.keys():
  display(key)
  display(train_features[key].shape)
  display(train_features[key][0])

'mfcc'

(40, 20)

array([0.7427209 , 0.20581514, 0.13455339, 0.43117392, 0.44616732,
       0.445525  , 0.46254006, 0.5670132 , 0.39506927, 0.42854863,
       0.2934668 , 0.39010987, 0.21329486, 0.22916535, 0.19343816,
       0.16317555, 0.10437053, 0.23615992, 0.0448035 , 0.27527472],
      dtype=float32)

'chroma'

(40, 12)

array([0.61081326, 0.6407694 , 0.7264329 , 0.7448724 , 0.6790618 ,
       0.7163921 , 0.5891423 , 0.6046873 , 0.6165784 , 0.5552559 ,
       0.5983539 , 0.60385174], dtype=float32)

'rms'

(40, 1)

array([0.05255991], dtype=float32)

'spectral_centroid'

(40, 1)

array([0.76229584], dtype=float32)

'melspectrogram'

(40, 20)

array([0.5381515 , 0.37269425, 0.37597787, 0.53354734, 0.56264013,
       0.6113426 , 0.6772857 , 0.73664606, 0.78619957, 0.91693234,
       0.96727914, 0.98384106, 0.9828732 , 0.9606077 , 0.9671836 ,
       0.6439813 , 0.64516133, 0.743132  , 0.81357414, 0.8961234 ],
      dtype=float32)

'continent'

(40,)

'EUROPE'

'type'

(40,)

'call'

'rating'

(40,)

3.0

In [14]:
val_y = features.val_y
val_y = np.array(val_y)

display(val_y.shape)
display(val_y[:5])

(13,)

array(['comsan', 'eaywag1', 'eaywag1', 'eaywag1', 'eaywag1'], dtype='<U7')

In [15]:
val_features = features.val_features

for key in val_features.keys():
  display(key)
  display(val_features[key].shape)
  display(val_features[key][0])

'mfcc'

(13, 20)

array([-0.09305231,  1.104807  ,  1.2074847 ,  1.5024759 ,  1.1166075 ,
        1.1644051 ,  0.8122131 ,  1.2262616 ,  0.73352337,  0.7984767 ,
        0.7414374 ,  0.95097125,  1.3437722 ,  0.9253728 ,  1.0289221 ,
        0.79905325,  0.8307996 ,  0.9090003 ,  0.7373432 ,  0.93721193],
      dtype=float32)

'chroma'

(13, 12)

array([0.09687231, 0.09037615, 0.12890504, 0.22399275, 0.40237024,
       0.6029498 , 0.85613585, 0.89852566, 0.86298704, 0.8093161 ,
       0.56014264, 0.2702567 ], dtype=float32)

'rms'

(13, 1)

array([0.11229729], dtype=float32)

'spectral_centroid'

(13, 1)

array([0.21533456], dtype=float32)

'melspectrogram'

(13, 20)

array([ 0.8768805 ,  0.3380551 ,  0.22273085,  0.00999372, -0.09355186,
       -0.07294122, -0.06786255, -0.20101918, -0.29758716, -0.33090132,
       -0.22231796, -0.22743276, -0.2567322 , -0.2839716 , -0.2762019 ,
       -0.12873568,  0.07311958,  0.18702364, -0.04665495, -0.27313286],
      dtype=float32)

'continent'

(13,)

'EUROPE'

'type'

(13,)

'call'

'rating'

(13,)

5.0